### ISSUE TITLE
Error when running Invoke-PSCodeHealth

### ISSUE THREAD

**Issue by Tiberriver256** [MathieuBuisson/PSCodeHealth#5]
## Expected Behavior
Invoke-PSCodeHealth should run tests.

## Current Behavior
Running Invoke-PSCodeHealth produces the following error:

```
Invoke-Pester : A parameter cannot be found that matches parameter name 'Show'.
At C:\Program Files\WindowsPowerShell\Modules\PSCodeHealth\0.1.139\Private\Metrics\Get-FunctionTestCoverage.ps1:51 char:127
+ ... ath = $SourcePath; Function = $FunctionName } -PassThru -Show None -V ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Pester], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Invoke-Pester
```

## Possible Solution
Perhaps a different version of Pester was released. Here is what I am currently using on my machine.

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.4.0      Pester                              {AfterAll, AfterEach, Assert-MockCalled, Assert-VerifiableMocks...}
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.139    PSCodeHealth                        {Get-PSCodeHealthComplianceRule, Invoke-PSCodeHealth, Test-PSCodeHealt...
```

**Comment by MathieuBuisson** [comment]
Thanks @Tiberriver256 for the feedback.  
Yes, your deduction was correct : the `Show` parameter of `Invoke-Pester` doesn't exist in version 3.4.0 of Pester.  
It was introduced in **Pester** 4.0 and this is why I listed Pester version 4.0.x (or later) in the requirements.  

That said, I think it would be fairly simple to handle this better in **PSCodeHealth**, and make it compatible with Pester version 3.4.x (and later).  
This `Show` parameter is the only **Pester** feature that **PSCodeHealth** uses which is different between versions 3.x and 4.0.x.  
And these older versions of **Pester** have an equivalent to `-Show None` : the `Quiet` switch parameter.  
So I could check for the Pester module version, and if it is older than 4.x, use `-Quiet` instead of `-Show None`.  

I will test to verify it is *that* simple. If it is, I will make the change.
